## Argo Events configuration
## Ref: https://github.com/argoproj/argo-events
##

## Custom resource configuration
crds:
  # 已经被argo-workflows安装了
  install: false
  # -- Keep CRDs on chart uninstall
  keep: true
  # -- Annotations to be added to all CRDs
  annotations: {}

global:
  image:
    # -- If defined, a repository applied to all Argo Events deployments
    repository: quay.io/argoproj/argo-events
    # -- Overrides the global Argo Events image tag whose default is the chart appVersion
    tag: ""
    # -- If defined, a imagePullPolicy applied to all Argo Events deployments
    imagePullPolicy: IfNotPresent