global:
  security:
    ## @param global.security.allowInsecureImages Allows skipping image verification
    allowInsecureImages: true
  redis:
    password: "<%= redisPassword %>"

## @param architecture Redis&reg; architecture. Allowed values: `standalone` or `replication`
##
architecture: standalone
## Redis&reg; Authentication parameters
## ref: https://github.com/bitnami/containers/tree/main/bitnami/redis#setting-the-server-password-on-first-run
##
auth:
  ## @param auth.enabled Enable password authentication
  ##
  enabled: true
  ## @param auth.sentinel Enable authentication on sentinels too
  ##
  sentinel: false
  
master:
  count: 1
  persistence:
    enabled: false

networkPolicy:
  enabled: false
  
serviceAccount:
  create: false